.TH BacklightTooler 1
.SH NAME
BacklightTooler \- collection of scripts to modify backlight
.SH SYNOPSIS
.B BacklightTooler
[\fBinc|dec|auto\fR \fIamount\fR]
[\fBpulse|toggle\fR]

.B BacklightToolerServiceToggle

.SH USAGE
For the tool to work, the systemd-service \fBBacklightToolerChangePermissions\fR
has to be enabled and started. The systemd-user timer
\fBBacklightTooler.timer\fR can be enabled to get automatic handling every 15
minutes. For changes of the default \fBauto\fR value, consider copying
\fB/usr/lib/systemd/user/BacklightTooler.service\fR to
\fB~/.config/systemd/user/\fR and edit the file from there.

.SH CONFIG

The configuration file \fI/etc/BacklightTooler.conf\fR has several options that
are explained in the file that's shipped with the package itself.

.SH EXAMPLE \fI.xbindkeysrc\fR

"BacklightTooler inc"
  XF86MonBrightnessUp

"BacklightTooler dec"
  XF86MonBrightnessDown

"systemctl --user start BacklightTooler.service"
  XF86Launch1

"systemctl --user stop BacklightTooler.timer; BacklightTooler toggle"
  XF86Launch2

"BacklightToolerServiceToggle"
  XF86Tools
