.TH backlight-tooler 1
.SH NAME
backlight-tooler \- collection of scripts to modify backlight
.SH SYNOPSIS
.B backlight-tooler -m [\fImode\fR] [-V [\fIamount\fR] -v -h -d -c [\fIfile\fR]
.br
.B -m
.br
.B auto
.br
automatic backlight setting with webcam
.br
.B set
.br
set backlight level to percentage given by \fB-V\fR flag
.br
.B inc / dec
.br
increase / decrease backlight level by percentage given by \fB-V\fR flag
.br
.B toggle
.br
toggle between display completely off and display fully lighted
.br
.B info
.br
show information that is useful for configuration
.br
.B -V
.br
percentage to the modes 'set', 'inc' or 'dec'.
.br
.B -v
.br
verbose logging
.br
.B -h
.br
show help
.br
.B -d
.br
show long help
.br
.B -c [\fIfile\fR]
.br
configuration file path that deviates from \fI/etc/backlight-tooler.conf\fR

.B backlight-tooler-service-toggle

.SH USAGE
The systemd-user timer \fBbacklight-tooler.timer\fR can be enabled / started to
get automatic handling every 15 minutes.

.SH CONFIG

.B /etc/backlight-tooler.conf
.br
Lines starting with \fB//\fR or \fB#\fR are ignored. Every option has to be in
the format \fIkey=value\fR without any whitespace or quotation marks. Possible
Options are in the default config file and visible with the \fB-d\fR flag.

