#!/bin/bash

# Small script for toggling the timer, use for keybindings

title="Automatic Backlight Control"
runstring="started - every 15 min"
stopstring="stopped"

systemctl --user is-active backlight-tooler.timer

if [ $? -eq 0 ]; then
    systemctl --user stop backlight-tooler.timer
    notify-send "$title" "$stopstring"
else
    systemctl --user start backlight-tooler.service
    systemctl --user start backlight-tooler.timer
    notify-send "$title" "$runstring"
fi
